[workspace]
authors = ["misilelab <misileminecord@gmail.com>", "GonGe1018 <chaeho1234@naver.com>"]
channels = ["conda-forge"]
name = "LESCdb"
platforms = ["linux-64", "win-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
msgpack-python = ">=1.1.1,<2"
openai = ">=1.95.1,<2"
scikit-learn = ">=1.7.0,<2"
datasets = ">=3.6.0,<4"
# faiss-cpu = ">=1.9.0,<2"

[pypi-dependencies]
cohere = "~=5.16.1"

[system-requirements]
cuda = "12.6"  # Optional, only for GPU support

[target.linux-64.dependencies]
# GPU dependencies are optional, enable via environment variables or manually install
faiss-gpu = ">=1.9.0,<2"

[target.linux-64.pypi-dependencies]
torch = "~=2.7.1,<3"

[target.win-64.dependencies]
# GPU dependencies are optional, enable via environment variables or manually install
faiss-gpu = ">=1.9.0,<2"

[target.win-64.pypi-dependencies]
torch = "~=2.7.1,<3"

[target.osx-64.dependencies]
faiss = ">=1.9.0,<2"  # macOS does not support GPU, use CPU version
pytorch = ">=2.7.1,<3"
