[workspace]
authors = ["misilelab <misileminecord@gmail.com>", "GonGe1018 <chaeho1234@naver.com>"]
channels = ["conda-forge", "pytorch"]
name = "LESCdb"
platforms = ["linux-64", "win-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
msgpack-python = ">=1.1.1,<2"
pytorch = ">=2.7.1,<3"
openai = ">=1.95.1,<2"
scikit-learn = ">=1.7.0,<2"
datasets = ">=3.6.0,<4"

[pypi-dependencies]
cohere = "~=5.16.1"

[target.osx-arm64.dependencies]
faiss = ">=1.9.0,<2"

[target.linux-64.dependencies]
faiss-gpu = ">=1.9.0,<2"

[target.win-64.dependencies]
faiss-gpu = ">=1.9.0,<2"

