[workspace]
authors = ["misilelab <misileminecord@gmail.com>", "GonGe1018 <chaeho1234@naver.com>"]
channels = ["conda-forge", "pytorch"]
name = "LESCdb"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
faiss-gpu = ">=1.9.0,<2"
msgpack-python = ">=1.1.1,<2"
pytorch = ">=2.7.1,<3"
