[workspace]
authors = ["misilelab <misileminecord@gmail.com>", "GonGe1018 <chaeho1234@naver.com>"]
channels = ["conda-forge", "pytorch", "cuda"]
name = "LESCdb"
platforms = ["linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
msgpack-python = ">=1.1.1,<2"
openai = ">=1.95.1,<2"
scikit-learn = ">=1.7.0,<2"
datasets = ">=3.6.0,<4"

[pypi-dependencies]
cohere = "~=5.16.1"

[system-requirements]
cuda = "11.6"

[target.linux-64.dependencies]
faiss-gpu = ">=1.9.0,<2"
pytorch-cuda = "<12"

[target.win-64.dependencies]
faiss-gpu = ">=1.9.0,<2"
pytorch-cuda = "<12"


